title:             Loyal SEO
email:             admin@seoleal.com
description:       Become Viral!
author:            Adam
baseurl:           ""
url:               "http://seoleal.com"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
