title:             Search Engine Optimizations
email:             admin@seoleal.com
description:       Figure out how to develop your traffic, improve your site, and increase traffic. Best how-tos for the SEO.
author:            Adam
baseurl:           ""
url:               "http://seoleal.com"

# Social Profiles
twitter_username:
github_username:
facebook_username: loyalseo

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
