title:             LoaylSEO
email:             admin@seoleal.com
description:       Search Engine Optimisation Techniques
author:            Adam
baseurl:           "/seoleal"
url:               "http://jeklog.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
